server:
  port: 7878
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?serverTimezone=GMT%2B8&amp&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    #此处的 序列化的策略 : 对属性值为 null 的不进行序列化
    default-property-inclusion: non_null
  mvc:
    #不抛出默认web服务器处理,自己处理 : 自己处理没有找到处理器异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      #不建立资源映射 : 自己处理没有找到处理器异常
      add-mappings: false
  servlet:
    multipart:
      #单体文件最大值
      max-file-size: 10MB
      #请求列表中文件总最大值
      max-request-size: 50MB
#  redis:
#    database: 0 #选择数据库索引,默认是 0
#    host: 192.168.1.4 #Redis 服务器地址
#    port: 6379 #Redis 使用的端口号
#    password: 123456 #Redis 连接密码 ,默认为空
  profiles:
#    active: company,product
#    active: home,product
#    active: product
#    active: company
    active: home
springdoc:
  swagger-ui:
    #是否允许生成swagger
    enabled: true
    #swagger-ui 访问路径 http://localhost:7878/swagger-ui/index.html，默认http://server:port/context-path/swagger-ui.html
    path: /swagger-ui.html
    #启用 CSRF 支持 ,跨站请求伪造
    csrf:
      enabled: true
    #包扫描路径,默认与 @SpringApplication 扫描的包相同
    #package-to-scan: com.lcl.pname.controller
project:
  global:
    conf:
      #文件服务器地址
      fileServerUrl: D:/lcl-temp/temp
      sessionUserKey: user
      userName: userName
      password: password
      captchaKey: captcha #自定义的 redis 存储验证码的 hash 表 key.
      checkCodeKey: Check-Code-Key #获取请求域中验证码 的 input key
      tokensKey: checkNum #获取请求头中生成的随机验证码的 redis key
  jwt:
    header: Authorization
    expire: 604800 #保留七天
    secret: qwertyuiopasdfghjklzxcvbnmasdfgh #32位,加解密使用的密匙