spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edu?serverTimezone=GMT%2B8&amp&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    locale: zh_CN
    #此处的 序列化的策略 : 对属性值不为 null 的不序列化
    default-property-inclusion: non_null
  mvc:
    #不抛出默认web服务器处理,自己处理 : 自己处理没有找到处理器异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      #不建立资源映射 : 自己处理没有找到处理器异常
      add-mappings: false
  servlet:
    multipart:
      #单体文件最大值
      max-file-size: 10MB
      #请求列表中文件总最大值
      max-request-size: 50MB
springdoc:
  swagger-ui:
    #是否允许生成swagger
    enabled: true
    #swagger-ui 访问路径 ，默认http://server:port/context-path/swagger-ui.html
    path: /swagger-ui.html
    #启用 CSRF 支持
    csrf:
      enabled: true
    #包扫描路径,默认与 @SpringApplication 扫描的包相同
    #package-to-scan: com.lcl.pname.controller
project:
  global:
    conf:
      #文件服务器地址
      fileServerUrl: D:/lcl-temp/temp